
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: 'certificate'
    repoURL: 'https://github.com/mathieulaude/appset-syncwave.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
